apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded 'admin'
  password: YWRtaW4=  # base64 encoded 'admin'
  root-password: YWRtaW4=  # base64 encoded 'admin' 